### ISSUE TITLE
Facebook Social Importer - Can't Load URL

### ISSUE THREAD

**Issue by alexrollin** [GeoDirectory/directory-starter#27]
"Connect your app" fails

![image](https://user-images.githubusercontent.com/114659/31718428-83435c16-b442-11e7-86fb-2654b374984b.png)

### Issue recreated here:

 - https://ppldb.com/supportdemoalex/wp-admin/admin.php?page=geodirectory&tab=facebook_integration&subtab=geodir_gdfi_options

### Related Documentation

 - https://wpgeodirectory.com/docs/social-importer-addon/#facebook

###  Related Issues

 - https://wpgeodirectory.com/support/topic/cant-load-url-the-domain-of-this-url-isnt-included-in-the-apps-domains/#post-401317
 - https://wpgeodirectory.com/support/topic/social-importer-errors/

### Possibly Related

 - https://www.mybboost.com/thread-error-191-can-t-load-url-using-facebook-login-app?pid=1332#pid1332

@kprajapatii @Stiofan

**Comment by Stiofan** [comment]
Hello,

Facebook changed things that affect new apps only.

I have added steps 10,11 and 12 here:
https://wpgeodirectory.com/docs/social-importer-addon/#facebook

I also released a update but the only real purpose of the update is to give the users the exact url that must be entered in the facebook app.

Thanks,

Stiofan
